ALTER TABLE leads ADD COLUMN IF NOT EXISTS owner TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS snoozed_until TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS flagged BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS verification_state TEXT DEFAULT 'unverified';
